from OWAF import Shard

from typing import Union

def test(g: int):
    def wrapper(func: callable):
        async def inner(*args, **kwargs):
            print('test1', g)
            return await func(*args, **kwargs)
        return inner
    return wrapper


def test2(k: int, l: int):
    def wrapper(func: callable):
        async def inner(*args, **kwargs):
            print('test2', k)
            return await func(*args, **kwargs)
        return inner
    return wrapper


class Index(Shard):
    shard_decorators = [test, test2]

    async def index(self, id: Union[float, int] = 0.0, name: str = "") -> str:
        '''explanation
        Say hello to the world

        :test: g=1
            :route: GET,POST: $/indexer
            :route: GET: $/
            :test2: k=2, l=3
                :route: GET: /
                :route: PUT,DELETE,POST: /indexed
            :end test2:
            :route: GET: /index/<float:id>
            :route: GET: /index/<int:id>/<string:name>
        :end test:
        :return: str: the response
        '''
        return f'Hello, World! {id} {self.shardname}'


@Shard.get('/x/indexer')
def indexer():
    return 'indexer'

class IndexApp(Shard):
    @Shard.get('x/index')
    async def index(self) -> str:
        return await self.env.index.index()

Index(debug=True, auto_import="sub")

# infos about env
"""
infos:

env:
{'action': {'abort': <function abort at 0x00007a5d44832e80>,
            'flash': <function flash at 0x00007a5d44832980>,
            'redirect': <function redirect at 0x00007a5d44832f20>},
 'after_this_request': <function after_this_request at 0x00007a5d44848e80>,
 'app': <OnlyWebAsync 'app'>,
 'app_ctx': <OWAF.ctx.AppContext object at 0x00007a5d43a03558>,
 'cache': {'index': {},
           'index/app': {},
           'second/index': {},
           'subsub/second/index': {}},
 'config': {'APPLICATION_ROOT': '/',
            'BACKGROUND_TASK_SHUTDOWN_TIMEOUT': 5,
            'BODY_TIMEOUT': 60,
            'DEBUG': False,
            'ENV': None,
            'EXPLAIN_TEMPLATE_LOADING': False,
            'MAX_CONTENT_LENGTH': 16777216,
            'MAX_COOKIE_SIZE': 4093,
            'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31),
            'PREFER_SECURE_URLS': False,
            'PRESERVE_CONTEXT_ON_EXCEPTION': None,
            'PROPAGATE_EXCEPTIONS': None,
            'RESPONSE_TIMEOUT': 60,
            'SECRET_KEY': None,
            'SEND_FILE_MAX_AGE_DEFAULT': datetime.timedelta(seconds=43200),
            'SERVER_NAME': None,
            'SESSION_COOKIE_DOMAIN': None,
            'SESSION_COOKIE_HTTPONLY': True,
            'SESSION_COOKIE_NAME': 'session',
            'SESSION_COOKIE_PATH': None,
            'SESSION_COOKIE_SAMESITE': None,
            'SESSION_COOKIE_SECURE': False,
            'SESSION_REFRESH_EACH_REQUEST': True,
            'TEMPLATES_AUTO_RELOAD': None,
            'TESTING': False,
            'TRAP_BAD_REQUEST_ERRORS': None,
            'TRAP_HTTP_EXCEPTIONS': False},
 'context': <OWAF.g of 'app'>,
 'copy_current_app_context': <function copy_current_app_context at 0x00007a5d44848fc0>,
 'copy_current_request_context': <function copy_current_request_context at 0x00007a5d44849060>,
 'copy_current_websocket_context': <function copy_current_websocket_context at 0x00007a5d44849100>,
 'current_app': <OnlyWebAsync 'app'>,
 'decorators': {'test': <function test at 0x00007a5d443faca0>,
                'test2': <function test2 at 0x00007a5d443faf20>},
 'has_app_context': <function has_app_context at 0x00007a5d448491a0>,
 'has_request_context': <function has_request_context at 0x00007a5d44849240>,
 'has_websocket_context': <function has_websocket_context at 0x00007a5d448492e0>,
 'index': <__main__.Index object at 0x00007a5d444d1a60>,
 'index_app': <__main__.IndexApp object at 0x00007a5d443902f8>,
 'jsonify': <function jsonify at 0x00007a5d449c5240>,
 'logger': <Logger app (WARNING)>,
 'make': {'push_promise': <function make_push_promise at 0x00007a5d448328e0>,
          'response': <function make_response at 0x00007a5d44832840>},
 'master': <__main__.Index object at 0x00007a5d444d1a60>,
 'render_template': <function render_template at 0x00007a5d445657e0>,
 'request': <Request 'http://127.0.0.1:5000/index/app/x/index' [GET]>,
 'routes': {'/': {'absolute': True,
                  'bare_callable': <bound method Index.index of <__main__.Index object at 0x00007a5d444d1a60>>,
                  'bare_callable_signature': {'coherent': False,
                                              'full_signature': <Signature (id: Union[float, int] = 0.0, name: str = '') -> str>,
                                              'input': {'id': [typing.Union[float, int]],
                                                        'name': [<class 'str'>]},
                                              'output': <class 'str'>},
                  'bare_path': '$/',
                  'callable': <function test.<locals>.wrapper.<locals>.inner at 0x00007a5d443fb100>,
                  'endpoint': '.',
                  'from_decorator': False,
                  'method': ['GET'],
                  'owner_class': <__main__.Index object at 0x00007a5d444d1a60>,
                  'path': '/',
                  'route_signature': [],
                  'shardname': 'index',
                  'wrappers': [(<function test at 0x00007a5d443faca0>,
                                {'g': 1})]},
            '/index/': {'absolute': False,
                        'bare_callable': <bound method Index.index of <__main__.Index object at 0x00007a5d444d1a60>>,
                        'bare_callable_signature': {'coherent': False,
                                                    'full_signature': <Signature (id: Union[float, int] = 0.0, name: str = '') -> str>,
                                                    'input': {'id': [typing.Union[float, int]],
                                                              'name': [<class 'str'>]},
                                                    'output': <class 'str'>},
                        'bare_path': '/',
                        'callable': <function test.<locals>.wrapper.<locals>.inner at 0x00007a5d443fafc0>,
                        'endpoint': '.index.',
                        'from_decorator': False,
                        'method': ['GET'],
                        'owner_class': <__main__.Index object at 0x00007a5d444d1a60>,
                        'path': '/index/',
                        'route_signature': [],
                        'shardname': 'index',
                        'wrappers': [(<function test at 0x00007a5d443faca0>,
                                      {'g': 1}),
                                     (<function test2 at 0x00007a5d443faf20>,
                                      {'k': 2, 'l': 3})]},
            '/index/app/x/index': {'absolute': False,
                                   'bare_callable': <bound method IndexApp.index of <__main__.IndexApp object at 0x00007a5d443902f8>>,
                                   'bare_callable_signature': {'coherent': -1,
                                                               'full_signature': <Signature () -> str>,
                                                               'input': None,
                                                               'output': <class 'str'>},
                                   'bare_path': 'x/index',
                                   'callable': <bound method IndexApp.index of <__main__.IndexApp object at 0x00007a5d443902f8>>,
                                   'endpoint': '.index.app.x.index',
                                   'from_decorator': True,
                                   'method': ['GET'],
                                   'owner_class': <__main__.IndexApp object at 0x00007a5d443902f8>,
                                   'path': '/index/app/x/index',
                                   'route_signature': [],
                                   'shardname': 'index/app',
                                   'wrappers': []},
            '/index/index/<float:id>': {'absolute': False,
                                        'bare_callable': <bound method Index.index of <__main__.Index object at 0x00007a5d444d1a60>>,
                                        'bare_callable_signature': {'coherent': False,
                                                                    'full_signature': <Signature (id: Union[float, int] = 0.0, name: str = '') -> str>,
                                                                    'input': {'id': [typing.Union[float, int]],
                                                                              'name': [<class 'str'>]},
                                                                    'output': <class 'str'>},
                                        'bare_path': '/index/<float:id>',
                                        'callable': <function test.<locals>.wrapper.<locals>.inner at 0x00007a5d443fad40>,
                                        'endpoint': '.index.index.float.id',
                                        'from_decorator': False,
                                        'method': ['GET'],
                                        'owner_class': <__main__.Index object at 0x00007a5d444d1a60>,
                                        'path': '/index/index/<float:id>',
                                        'route_signature': [('id',
                                                             <class 'float'>)],
                                        'shardname': 'index',
                                        'wrappers': [(<function test at 0x00007a5d443faca0>,
                                                      {'g': 1})]},
            '/index/index/<int:id>/<string:name>': {'absolute': False,
                                                    'bare_callable': <bound method Index.index of <__main__.Index object at 0x00007a5d444d1a60>>,
                                                    'bare_callable_signature': {'coherent': False,
                                                                                'full_signature': <Signature (id: Union[float, int] = 0.0, name: str = '') -> str>,
                                                                                'input': {'id': [typing.Union[float, int]],
                                                                                          'name': [<class 'str'>]},
                                                                                'output': <class 'str'>},
                                                    'bare_path': '/index/<int:id>/<string:name>',
                                                    'callable': <function test.<locals>.wrapper.<locals>.inner at 0x00007a5d443fac00>,
                                                    'endpoint': '.index.index.int.id.string.name',
                                                    'from_decorator': False,
                                                    'method': ['GET'],
                                                    'owner_class': <__main__.Index object at 0x00007a5d444d1a60>,
                                                    'path': '/index/index/<int:id>/<string:name>',
                                                    'route_signature': [('id',
                                                                         <class 'int'>),
                                                                        ('name',
                                                                         <class 'str'>)],
                                                    'shardname': 'index',
                                                    'wrappers': [(<function test at 0x00007a5d443faca0>,
                                                                  {'g': 1})]},
            '/index/indexed': {'absolute': False,
                               'bare_callable': <bound method Index.index of <__main__.Index object at 0x00007a5d444d1a60>>,
                               'bare_callable_signature': {'coherent': False,
                                                           'full_signature': <Signature (id: Union[float, int] = 0.0, name: str = '') -> str>,
                                                           'input': {'id': [typing.Union[float, int]],
                                                                     'name': [<class 'str'>]},
                                                           'output': <class 'str'>},
                               'bare_path': '/indexed',
                               'callable': <function test.<locals>.wrapper.<locals>.inner at 0x00007a5d443fade0>,
                               'endpoint': '.index.indexed',
                               'from_decorator': False,
                               'method': ['PUT', 'DELETE', 'POST'],
                               'owner_class': <__main__.Index object at 0x00007a5d444d1a60>,
                               'path': '/index/indexed',
                               'route_signature': [],
                               'shardname': 'index',
                               'wrappers': [(<function test at 0x00007a5d443faca0>,
                                             {'g': 1}),
                                            (<function test2 at 0x00007a5d443faf20>,
                                             {'k': 2, 'l': 3})]},
            '/indexer': {'absolute': True,
                         'bare_callable': <bound method Index.index of <__main__.Index object at 0x00007a5d444d1a60>>,
                         'bare_callable_signature': {'coherent': False,
                                                     'full_signature': <Signature (id: Union[float, int] = 0.0, name: str = '') -> str>,
                                                     'input': {'id': [typing.Union[float, int]],
                                                               'name': [<class 'str'>]},
                                                     'output': <class 'str'>},
                         'bare_path': '$/indexer',
                         'callable': <function test.<locals>.wrapper.<locals>.inner at 0x00007a5d443fb1a0>,
                         'endpoint': '.indexer',
                         'from_decorator': False,
                         'method': ['GET', 'POST'],
                         'owner_class': <__main__.Index object at 0x00007a5d444d1a60>,
                         'path': '/indexer',
                         'route_signature': [],
                         'shardname': 'index',
                         'wrappers': [(<function test at 0x00007a5d443faca0>,
                                       {'g': 1})]},
            '/second/index/': {'absolute': False,
                               'bare_callable': <bound method Index.index of <sub.second.Index object at 0x00007a5d443900c8>>,
                               'bare_callable_signature': {'coherent': True,
                                                           'full_signature': <Signature () -> str>,
                                                           'input': {},
                                                           'output': <class 'str'>},
                               'bare_path': '/',
                               'callable': <function test.<locals>.wrapper.<locals>.inner at 0x00007a5d44359240>,
                               'endpoint': '.second.index.',
                               'from_decorator': False,
                               'method': ['GET'],
                               'owner_class': <sub.second.Index object at 0x00007a5d443900c8>,
                               'path': '/second/index/',
                               'route_signature': [],
                               'shardname': 'second/index',
                               'wrappers': [(<function test at 0x00007a5d443faca0>,
                                             {'g': 1})]},
            '/subsub/second/index/': {'absolute': False,
                                      'bare_callable': <bound method Index.index of <sub.subsub.second.Index object at 0x00007a5d44377f68>>,
                                      'bare_callable_signature': {'coherent': True,
                                                                  'full_signature': <Signature () -> str>,
                                                                  'input': {},
                                                                  'output': <class 'str'>},
                                      'bare_path': '/',
                                      'callable': <function test.<locals>.wrapper.<locals>.inner at 0x00007a5d443591a0>,
                                      'endpoint': '.subsub.second.index.',
                                      'from_decorator': False,
                                      'method': ['GET'],
                                      'owner_class': <sub.subsub.second.Index object at 0x00007a5d44377f68>,
                                      'path': '/subsub/second/index/',
                                      'route_signature': [],
                                      'shardname': 'subsub/second/index',
                                      'wrappers': [(<function test at 0x00007a5d443faca0>,
                                                    {'g': 1})]},
            '/x/indexer': {'absolute': True,
                           'bare_callable': <function indexer at 0x00007a5d443fb240>,
                           'bare_callable_signature': {'coherent': -1,
                                                       'full_signature': <Signature ()>,
                                                       'input': None,
                                                       'output': None},
                           'bare_path': '$/x/indexer',
                           'callable': <function indexer at 0x00007a5d443fb240>,
                           'endpoint': '.x.indexer',
                           'from_decorator': True,
                           'method': ['GET'],
                           'owner_class': None,
                           'path': '/x/indexer',
                           'route_signature': [],
                           'shardname': None,
                           'wrappers': []}},
 'second_index': <sub.second.Index object at 0x00007a5d443900c8>,
 'session': <NullSession {}>,
 'signals': {'appcontext_popped': <blinker.base.NamedSignal object at 0x00007a5d44845948; 'appcontext-popped'>,
             'appcontext_pushed': <blinker.base.NamedSignal object at 0x00007a5d44845980; 'appcontext-pushed'>,
             'appcontext_tearing_down': <blinker.base.NamedSignal object at 0x00007a5d4475caa0; 'appcontext-tearing-down'>,
             'before_render_template': <blinker.base.NamedSignal object at 0x00007a5d4475c790; 'before-render-template'>,
             'got_request_exception': <blinker.base.NamedSignal object at 0x00007a5d4475c918; 'got-request-exception'>,
             'got_websocket_exception': <blinker.base.NamedSignal object at 0x00007a5d4475ca68; 'got-websocket-exception'>,
             'message_flashed': <blinker.base.NamedSignal object at 0x00007a5d4481f520; 'message-flashed'>,
             'request_finished': <blinker.base.NamedSignal object at 0x00007a5d4475c838; 'request-finished'>,
             'request_started': <blinker.base.NamedSignal object at 0x00007a5d4475c800; 'request-started'>,
             'request_tearing_down': <blinker.base.NamedSignal object at 0x00007a5d4475c870; 'request-tearing-down'>,
             'signals_available': True,
             'template_rendered': <blinker.base.NamedSignal object at 0x00007a5d4475c7c8; 'template-rendered'>,
             'websocket_finished': <blinker.base.NamedSignal object at 0x00007a5d4475c9f8; 'websocket-finished'>,
             'websocket_started': <blinker.base.NamedSignal object at 0x00007a5d4475c950; 'websocket-started'>,
             'websocket_tearing_down': <blinker.base.NamedSignal object at 0x00007a5d4475ca30; 'websocket-tearing-down'>},
 'slaves': {'index_app': <__main__.IndexApp object at 0x00007a5d443902f8>,
            'second_index': <sub.second.Index object at 0x00007a5d443900c8>,
            'subsub_second_index': <sub.subsub.second.Index object at 0x00007a5d44377f68>},
 'subsub_second_index': <sub.subsub.second.Index object at 0x00007a5d44377f68>,
 'template': {'render': <function render_template at 0x00007a5d445657e0>,
              'render_string': <function render_template_string at 0x00007a5d44565880>,
              'send_file': <function send_file at 0x00007a5d44832de0>,
              'send_from_directory': <function send_from_directory at 0x00007a5d44832d40>,
              'stream_string': <function stream_template_string at 0x00007a5d44565b00>,
              'stream_template': <function stream_template at 0x00007a5d44565a60>},
 'url_for': <function url_for at 0x00007a5d44832b60>,
 'url_map': Map([<Rule '/static/<filename>' (GET, OPTIONS, HEAD) -> static>,
 <Rule '/indexer' (GET, POST, OPTIONS, HEAD) -> .indexer>,
 <Rule '/' (GET, OPTIONS, HEAD) -> .>,
 <Rule '/index/' (GET, OPTIONS, HEAD) -> .index.>,
 <Rule '/index/indexed' (PUT, DELETE, POST, OPTIONS) -> .index.indexed>,
 <Rule '/index/index/<id>' (GET, OPTIONS, HEAD) -> .index.index.float.id>,
 <Rule '/index/index/<id>/<name>' (GET, OPTIONS, HEAD) -> .index.index.int.id.string.name>,
 <Rule '/x/indexer' (GET, OPTIONS, HEAD) -> .x.indexer>,
 <Rule '/index/app/x/index' (GET, OPTIONS, HEAD) -> .index.app.x.index>,
 <Rule '/second/index/' (GET, OPTIONS, HEAD) -> .second.index.>,
 <Rule '/subsub/second/index/' (GET, OPTIONS, HEAD) -> .subsub.second.index.>]),
 'utils': {'DotDict': <class 'OWAF.shards.utils.DotDict'>,
           'ShardType': <class 'OWAF.shards.modules.shardtype.ShardType'>,
           'explore_and_import': <function explore_and_import at 0x00007a5d443dbc40>},
 'websocket': <LocalProxy unbound>,
 'websocket_ctx': <LocalProxy unbound>}
"""
